process.env.TS_NODE_COMPILER_OPTIONS = JSON.stringify({ module: 'commonjs' });
process.env.SECRET_KEY = process.env.SECRET_KEY || 'test-only-secret';
require('ts-node/register');
require('tsconfig-paths/register');
require('./application/transactions.test.ts');
require('./application/pairs.test.ts');
require('./application/transaction-groups.test.ts');
require('./infrastructure/server-kv-repositories.test.ts');
require('./infrastructure/redis-key-value-store.test.ts');
require('./api/read-api.test.ts');
require('./infrastructure/http-read-repositories.test.ts');
