process.env.TS_NODE_COMPILER_OPTIONS = JSON.stringify({ module: 'commonjs' });
process.env.SECRET_KEY = process.env.SECRET_KEY || 'test-only-secret';
require('ts-node/register');
require('tsconfig-paths/register');
require('./application/transactions.test.ts');
require('./application/pairs.test.ts');
require('./application/transaction-groups.test.ts');
require('./application/auth-login.test.ts');
require('./application/trading-bots.test.ts');
require('./application/market-data.test.ts');
require('./application/backfill-candles.test.ts');
require('./infrastructure/server-kv-repositories.test.ts');
require('./infrastructure/redis-key-value-store.test.ts');
require('./infrastructure/redis-health-check.test.ts');
require('./infrastructure/prisma-health-check.test.ts');
require('./infrastructure/prisma-repositories.test.ts');
require('./infrastructure/prisma-bot-budget-repository.test.ts');
require('./infrastructure/prisma-auth-repository.test.ts');
require('./infrastructure/binance-rest-market-data-source.test.ts');
require('./infrastructure/kv-export-audit.test.ts');
require('./infrastructure/redis-database-tooling.test.ts');
require('./api/read-api.test.ts');
require('./infrastructure/http-read-repositories.test.ts');
