"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { StrategyDto } from "@/src/modules/strategy/dto/StrategyDto";
import type { StrategyDefinitionV1, StrategyValidationIssue } from "@/src/modules/strategy/domain/StrategyDefinition";
import type { BotDto } from "@/src/modules/bot/dto/BotDto";
import type { PairDto } from "@/src/modules/pair/dto/PairDto";
import type { StrategyPerformanceDto } from "@/pages/api/strategies/performance";
import { StrategyApiClient } from "./StrategyApiClient";
import { BotApiClient } from "./BotApiClient";
import { BotList } from "./BotList";
import { StrategyRuleBuilder, parseStrategyJson } from "./StrategyRuleBuilder";
import { newCondition } from "./strategyRuleTree";

const fresh = (): StrategyDefinitionV1 => ({ schemaVersion: 1, name: "New strategy", entryPolicy: { trigger: "ON_FALSE_TO_TRUE", cooldownCandles: 0 }, entry: { all: [newCondition("RSI")] }, exit: { all: [{ indicator: "RSI", period: 14, operator: "GTE", value: 80 }] } });

export default function StrategiesAndBots() {
  const strategyApi = useMemo(() => new StrategyApiClient(), []); const botApi = useMemo(() => new BotApiClient(), []);
  const [strategies, setStrategies] = useState<StrategyDto[]>([]); const [bots, setBots] = useState<BotDto[]>([]); const [pairs, setPairs] = useState<PairDto[]>([]);
  const [performance, setPerformance] = useState<StrategyPerformanceDto[]>([]); const [loading, setLoading] = useState(true); const [showArchived, setShowArchived] = useState(false);
  const [editing, setEditing] = useState<string | null>(null); const [definition, setDefinition] = useState(fresh); const [json, setJson] = useState(() => JSON.stringify(fresh(), null, 2));
  const [description, setDescription] = useState(""); const [jsonError, setJsonError] = useState(""); const [issues, setIssues] = useState<StrategyValidationIssue[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [s, b, p, stats] = await Promise.all([strategyApi.list(), botApi.list(), botApi.listPairs(), strategyApi.performance()]); setStrategies(s); setBots(b); setPairs(p); setPerformance(stats); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not load strategies and bots"); } finally { setLoading(false); } }, [botApi, strategyApi]);
  useEffect(() => { void load(); }, [load]);
  const update = (next: StrategyDefinitionV1) => { setDefinition(next); setJson(JSON.stringify(next, null, 2)); setJsonError(""); setIssues([]); };
  const editJson = (value: string) => { setJson(value); const parsed = parseStrategyJson(value); setJsonError(parsed.error); setIssues(parsed.issues); if (parsed.definition) setDefinition(parsed.definition); };
  const select = (id: string) => { setEditing(id || "new"); setMessage(""); const strategy = strategies.find((s) => s.id === id); if (!strategy) { const next = fresh(); setDescription(""); update(next); return; } const version = strategy.versions.at(-1)!; setDescription(strategy.description); update(structuredClone(version.definition)); };
  const save = async () => { setBusy(true); setMessage(""); try { if (jsonError) throw new Error("Fix the strategy JSON before saving."); const validation = await strategyApi.validate(definition); setIssues(validation.issues); if (!validation.valid) throw new Error("The strategy contains validation errors."); if (editing && editing !== "new") { await strategyApi.update(editing, { name: definition.name, description }); await strategyApi.addVersion(editing, definition); } else await strategyApi.create(definition.name, description, definition); await load(); setEditing(null); setMessage("Strategy saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save strategy"); } finally { setBusy(false); } };
  const archive = async (strategy: StrategyDto) => { setBusy(true); try { const changed = await strategyApi.update(strategy.id, { archived: !strategy.archivedAt }); setStrategies((all) => all.map((s) => s.id === changed.id ? changed : s)); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not archive strategy"); } finally { setBusy(false); } };
  const remove = async (strategy: StrategyDto) => { if (!window.confirm(`Permanently delete “${strategy.name}”, every bot using it, and all connected runs and trading records? This cannot be undone.`)) return; setBusy(true); try { await strategyApi.delete(strategy.id); setStrategies((all) => all.filter((s) => s.id !== strategy.id)); setBots((all) => all.filter((bot) => !strategy.versions.some((v) => v.id === bot.strategyVersionId))); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not delete strategy"); } finally { setBusy(false); } };
  const stats = (id: string) => { const result = performance.find((item) => item.strategyId === id); return { plus: result?.profitableRuns ?? 0, minus: result?.losingRuns ?? 0 }; };
  const visible = strategies.filter((s) => showArchived || !s.archivedAt);
  return <div className="mx-auto min-w-0 max-w-[1600px] text-slate-100"><section className="mb-8 overflow-hidden rounded-2xl border border-slate-700 bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-700 p-4 sm:p-5"><div><p className="text-xs font-semibold uppercase tracking-[.3em] text-emerald-400">Reusable logic</p><h2 className="mt-1 text-2xl font-bold">Strategies</h2></div><div className="flex flex-wrap items-center gap-4"><label className="text-sm"><input className="mr-2" type="checkbox" checked={showArchived} onChange={(e) => setShowArchived(e.target.checked)} />Show archived</label><button onClick={() => select("")} className="rounded-xl border border-cyan-600 px-4 py-2 text-sm text-cyan-200">+ New strategy</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-950/60 text-xs uppercase text-slate-400"><tr><th className="px-4 py-3">Name</th><th>Description</th><th>Versions</th><th className="text-emerald-400">Profitable</th><th className="text-rose-400">Losing</th><th></th></tr></thead><tbody className="divide-y divide-slate-800">{visible.map((strategy) => { const run = stats(strategy.id); return <tr key={strategy.id} className={strategy.archivedAt ? "text-slate-500" : ""}><td className="px-4 py-4 font-semibold">{strategy.name}{strategy.archivedAt && <span className="ml-2 text-xs">Archived</span>}</td><td className="max-w-xs truncate">{strategy.description || "—"}</td><td>{strategy.versions.length}</td><td className="font-bold text-emerald-400">+{run.plus}</td><td className="font-bold text-rose-400">−{run.minus}</td><td className="whitespace-nowrap px-4"><button disabled={busy || !!strategy.archivedAt} onClick={() => select(strategy.id)} aria-label={`Edit ${strategy.name}`} className="text-lg disabled:opacity-30">✎</button><button disabled={busy} onClick={() => void archive(strategy)} className="ml-3 text-xs text-amber-300">{strategy.archivedAt ? "Restore" : "Archive"}</button><button disabled={busy} onClick={() => void remove(strategy)} className="ml-3 text-xs text-rose-400">Delete</button></td></tr>; })}{!loading && !visible.length && <tr><td colSpan={6} className="p-8 text-center text-slate-500">No strategies to display.</td></tr>}</tbody></table></div></section>
  {editing && <section className="mb-8 rounded-2xl border border-cyan-800 bg-slate-950/40 p-3 sm:p-5"><div className="mb-5 flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-bold">Strategy rule builder</h2><p className="text-sm text-slate-400">The visual rules and editable JSON always describe the same strategy.</p></div><button onClick={() => setEditing(null)} className="self-start rounded-lg border border-slate-600 px-3 py-2 text-sm">Close</button></div><StrategyRuleBuilder definition={definition} onChange={update} json={json} onJsonChange={editJson} jsonError={jsonError} description={description} onDescriptionChange={setDescription} issues={issues} sideBySide /><div className="mt-5 flex justify-end"><button disabled={busy || !!jsonError} onClick={() => void save()} className="rounded-xl bg-cyan-700 px-6 py-3 font-semibold disabled:opacity-40">{busy ? "Saving…" : editing === "new" ? "Create strategy" : "Save new version"}</button></div></section>}
  {message && <p role="status" className="mb-5 rounded-xl border border-slate-700 bg-slate-900 p-4 text-sm">{message}</p>}<BotList api={botApi} bots={bots} pairs={pairs} strategies={strategies} loading={loading} onChanged={(bot) => setBots((all) => all.map((b) => b.id === bot.id ? bot : b))} onDeleted={(id) => setBots((all) => all.filter((b) => b.id !== id))} /></div>;
}
